#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server(load balancer server).

sudo apt-get -y update
sudo apt-get -y install haproxy

echo "
frontend Chynet
    bind *:80
    default_backend Chynetech

backend Chynetech
    balance roundrobin
    server 141809-web-01 18.204.9.21:80 check
    server 141809-web-02 100.25.104.210:80 check
" >> /etc/haproxy/haproxy.cfg

sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

sudo service haproxy restart
